### ISSUE TITLE
request / response 객체 외에 dto 객체를 추가로 사용하는 이유가 궁금합니다!

### ISSUE THREAD

**Issue by dompoo** [doljae/kopring-starter#1]
CustomerService, CustomerController 코드를 보니까,

컨트롤러가 준 request를 dto로 가공해서 서비스가 사용하고,
서비스가 준 dto를 response로 가공해서 컨트롤러가 사용하는 구조란 것은 알았습니다!

dto 없이 서비스가 바로 request로 비즈니스 로직을 실행하고, response를 줄 수도 있을텐데,
따로 dto 객체룰 둔 이유가 궁금합니다.

**Comment by doljae** [comment]
@Dompoo 님 안녕하세요.

이 프로젝트의 **Controller**, **Service** 계층의 상호 작용은 아래 방법으로 하고 있습니다.

- Controller의 request를 그대로 Service로 전달
- Controller는 Service의 응답을 response로 가공해서 반환

우선 질문 주신 Service의 응답을 response로 가공해서 반환한 이유는 여러 가지가 있는데요.

- Service 계층의 내부 구현과 세부 사항을 노출하지 않고 클라이언트(API를 호출한 쪽)에 필요한 정보만 선별해서 반환하기 위해서
- 같은 Service 로직을 사용하지만, API 스펙이나 버전에 따라서 다른 형식의 응답을 제공하기 위해서
- Service 계층이 Controller 계층에서 사용하는 클래스에 의존하지 않게 해서 변경 발생 시 수정 사항을 최소화하기 위해서
(다만 현재 Controller의 request를 그대로 Service에 전달하고 있긴 한데 이 부분도 적용하면 response 객체를 사용한 것과 유사한 장점을 누릴 수 있습니다.)

정도가 있을 것 같습니다.

정리하면 Controller와 Service 사이에 클라이언트의 응답으로 나가기 전에 확인해야 하는 검증, 변환, 필터링 등을 하는 response 객체라는 보이지 않는 계층에서 하고 있다고 봐주시면 될 것 같습니다.

일반적으로 Controller의 API와 이에 대응하는 Service의 함수(메서드)가 1대1로 매칭되어서 Service에서 반환한 값(객체)을 그대로 Controller에서도 API 응답으로 반환하곤 하는데요. request, response 객체를 두어서 약간의 복잡도와 몇 가지 장점을 얻었다고 생각해주시면 좋을 것 같습니다.

다만 이 프로젝트 코드 베이스는 README에서 설명해 드린 것처럼 `Kotlin과 Spring의 조합에 대한 정보 전달`을 목적으로 만든 것이라 말씀 주신 것처럼 계층 관계, 의존성, 패키지, 모듈 등 프로젝트 구조와 관련된 것들에 대해서는 더 좋은 자료나 레포지토리를 참고해주시면 좋을 것 같습니다.

꼼꼼히 봐주셔서 감사합니다.
그 외에 궁금한 점이 있으시다면 편하게 코멘트 부탁드립니다 🙂

**Comment by dompoo** [comment]
감사합니다! 프로젝트와 영상 보며 많은 도움을 받고 있습니다.
